---
# indicação dos hosts que devem receber a atualização
- hosts: all
  #campo obrigatório task para informar as tarefas a serem executadas.
  tasks:
    # Exemplo utilizando o modo mais novo e compacto para a instalação de multiplas dependencias.
    - name: 'Instalando os pacotes em forma de loop com with_items'
      apt:
        name: ['php5', 'apache2', 'libapache2-mod-php5', 'php5-gd', 'libssh2-php', 'php5-mcrypt', 'mysql-server-5.6', 'python-mysqldb', 'php5-mysql']
        state: latest
      become: yes
    # Exemplo de uma instrução de atualização unica.
    - name: 'Instalando PHP'
      apt: 
        name: php5
        state: latest
      become: yes
    - name: 'Instalando Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instala modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes
    # Como é feita a configuração de um banco no playbook do ansible.
    # name: 'Criação e Configuração do Banco MySQL'
    - name: "Cria o banco do MySQL"
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present    # status possiveis no mySQL: present (criar banco) | absent (para exclusao) | dump (retirar informações de estruturas) | import (para importar informações ao banco)
        
    